#!/usr/bin/env bash

"${HOME}/bin/check-display"
"${HOME}/bin/startups"
sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width 0.5
bspc config window_gap 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a {Steam,lutris} desktop='^2'
bspc rule -a zathura desktop='^3'
bspc rule -a {audacity,hydrogen,lmms} desktop='^5'
bspc rule -a firefox desktop='^6'
bspc rule -a keepassxc desktop='^10'
bspc rule -a Signal desktop='^10'

#bspc rule -a scratchpad sticky=on state=floating hidden=on
